#ifndef EURO_EUCLIDEAN_H_
#define EURO_EUCLIDEAN_H_

enum EditField {
	EDIT_NONE,
	EDIT_A,
	EDIT_B,
	EDIT_C,
	EDIT_D,
};

enum EditSubField {
	SUBEDIT_LENGTH,
	SUBEDIT_PULSES,
	SUBEDIT_PULSES_ATT,
	SUBEDIT_OFFSET,
	SUBEDIT_OFFSET_ATT,

	NUM_SUBEDIT,
};


#define MAX_LENGTH 128
#define MAX_DISP_WIDTH 17
#define CALIBRATE_USECS 10000
#define CALIBRATE_FILTER_CONST 0.001f

#define SAVE_VERSION 3

#endif // EURO_EUCLIDEAN_H_